{
  "openapi": "3.0.0",
  "info": {
    "title": "BlockchainJS API",
    "version": "1.0",
    "description": "An API to manage the decentralized Blockchain network.",
    "contact": {
      "name": "Christopher Ortiz Montero",
      "url": "https://github.com/christophermontero",
      "email": "cgortizm21@gmail.com"
    },
    "termsOfService": "http://swagger.io/terms",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3001",
      "description": "node1"
    },
    {
      "description": "node2",
      "url": "http://localhost:3002"
    },
    {
      "url": "http://localhost:3003",
      "description": "node3"
    },
    {
      "url": "http://localhost:3004",
      "description": "node4"
    }
  ],
  "paths": {
    "/api/v1/blockchain": {
      "get": {
        "summary": "Get blockchain",
        "operationId": "get-blockchain",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Blockchain"
                    }
                  ]
                },
                "examples": {
                  "blockchain-object": {
                    "$ref": "#/components/examples/blockchain"
                  }
                }
              }
            }
          }
        },
        "tags": [
          "blockchain"
        ],
        "description": "Get the entire Blockchain object."
      }
    },
    "/api/v1/transaction": {
      "post": {
        "summary": "Create transaction",
        "operationId": "post-transaction",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Transaction will be added in block 2"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "create-transaction": {
                    "value": {
                      "note": "Transaction will be added in block 2"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/bodyValidation"
          }
        },
        "description": "Create a new transaction into the Blockchain.",
        "requestBody": {
          "$ref": "#/components/requestBodies/transaction"
        },
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/mine": {
      "get": {
        "summary": "Mine block",
        "tags": [
          "mine"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "properties": {
                        "note": {
                          "type": "string"
                        },
                        "block": {
                          "$ref": "#/components/schemas/Block"
                        }
                      }
                    }
                  ],
                  "type": "object"
                },
                "examples": {
                  "mine-block": {
                    "value": {
                      "note": "New block mined successfully",
                      "block": {
                        "index": 2,
                        "timestamp": 1642010815329,
                        "transactions": [
                          {
                            "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                            "amount": 10,
                            "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                            "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                          }
                        ],
                        "nonce": 54068,
                        "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
                        "prevBlockHash": "0"
                      }
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/axiosError"
          }
        },
        "operationId": "get-mine",
        "description": "Add a new block to the Blockchain."
      }
    },
    "/api/v1/register-node": {
      "post": {
        "summary": "Register node",
        "operationId": "post-register-node",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "New node register successfully"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "register-node": {
                    "value": {
                      "note": "New node register successfully"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Node already exists"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "already-exists": {
                    "value": {
                      "note": "Node already exists"
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "register"
        ],
        "description": "Adds the url of the node to another node.",
        "requestBody": {
          "$ref": "#/components/requestBodies/registerNode"
        }
      }
    },
    "/api/v1/register-nodes-bulk": {
      "post": {
        "summary": "Register nodes bulk",
        "operationId": "post-register-nodes-bulk",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Bulk registration successfully"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "register-bulk": {
                    "value": {
                      "note": "Bulk registration successfully"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Bulk registration successfully"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "already-exists": {
                    "$ref": "#/components/examples/alreadyExist"
                  }
                }
              }
            }
          }
        },
        "tags": [
          "register"
        ],
        "description": "Adds multiple node urls to the entire network.",
        "requestBody": {
          "$ref": "#/components/requestBodies/networkNodes"
        }
      }
    },
    "/api/v1/register-broadcast-node": {
      "post": {
        "summary": "Register and broadcast node",
        "operationId": "post-register-broadcast-node",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "New node registered with network successfully"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "node-registered": {
                    "value": {
                      "note": "New node registered with network successfully"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Must be at least one node registered"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "zero-node": {
                    "value": {
                      "note": "Must be at least one node registered"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/axiosError"
          }
        },
        "tags": [
          "register"
        ],
        "description": "Aggregates the url of a node and transmits it to all nodes in the network.",
        "requestBody": {
          "$ref": "#/components/requestBodies/registerNode"
        }
      }
    },
    "/api/v1/transaction/broadcast": {
      "post": {
        "summary": "Create and broadcast transaction",
        "operationId": "post-transaction-broadcast",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "type": "object",
                  "x-examples": {
                    "example-1": {
                      "note": "Transaction created and broadcast successfully"
                    }
                  },
                  "properties": {
                    "note": {
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "transaction-broadcast": {
                    "value": {
                      "note": "Transaction created and broadcast successfully"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "$ref": "#/components/responses/axiosError"
          }
        },
        "description": "Create a new transaction and transmits it to all nodes in the network.",
        "requestBody": {
          "$ref": "#/components/requestBodies/transaction"
        },
        "tags": [
          "transaction"
        ]
      }
    },
    "/api/v1/receive-new-block": {
      "post": {
        "summary": "Receive new block",
        "operationId": "post-receive-block",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "x-examples": {
                    "example-1": {
                      "note": "New block received and accepted"
                    }
                  },
                  "allOf": [
                    {
                      "properties": {
                        "note": {
                          "type": "string"
                        },
                        "newBlock": {
                          "$ref": "#/components/schemas/Block"
                        }
                      }
                    }
                  ],
                  "type": "object"
                },
                "examples": {
                  "block-accepted": {
                    "value": {
                      "note": "New block received and accepted",
                      "newBlock": {
                        "index": 2,
                        "timestamp": 1642010815329,
                        "transactions": [
                          {
                            "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                            "amount": 10,
                            "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                            "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                          }
                        ],
                        "nonce": 54068,
                        "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
                        "prevBlockHash": "0"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "description": "",
                  "x-examples": {
                    "example-1": {
                      "note": "New block rejected"
                    }
                  },
                  "allOf": [
                    {
                      "properties": {
                        "note": {
                          "type": "string"
                        },
                        "": {
                          "$ref": "#/components/schemas/Block"
                        }
                      }
                    }
                  ],
                  "type": "object"
                },
                "examples": {
                  "block-rejected": {
                    "value": {
                      "note": "New block rejected",
                      "newBlock": {
                        "index": 2,
                        "timestamp": 1642010815329,
                        "transactions": [
                          {
                            "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                            "amount": 10,
                            "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                            "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                          }
                        ],
                        "nonce": 54068,
                        "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
                        "prevBlockHash": "0"
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "tags": [
          "transaction"
        ],
        "description": "Recive a new block and added to chain.",
        "requestBody": {
          "$ref": "#/components/requestBodies/newBlock"
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Blockchain": {
        "title": "Blockchain",
        "description": "",
        "x-examples": {},
        "type": "object",
        "properties": {
          "chain": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/Block"
            }
          },
          "pendingTransactions": {
            "type": "array",
            "description": "The pending transactions go here.",
            "items": {
              "$ref": "#/components/schemas/Transaction"
            }
          },
          "currentNodeUrl": {
            "type": "string"
          },
          "networkNodes": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      },
      "Block": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "title": "",
        "properties": {
          "index": {
            "type": "number"
          },
          "timestamp": {
            "type": "number"
          },
          "transactions": {
            "type": "array",
            "description": "When transactions are added to the Block, go here.",
            "items": {
              "$ref": "#/components/schemas/Transaction"
            }
          },
          "nonce": {
            "type": "number"
          },
          "hash": {
            "type": "string"
          },
          "prevBlockHash": {
            "type": "string"
          }
        }
      },
      "Transaction": {
        "description": "",
        "type": "object",
        "x-examples": {},
        "properties": {
          "transactionId": {
            "type": "string"
          },
          "amount": {
            "type": "number"
          },
          "sender": {
            "type": "string"
          },
          "recipient": {
            "type": "string"
          }
        }
      }
    },
    "responses": {
      "bodyValidation": {
        "description": "Bad Request",
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "_original": {
                    "amount": "a",
                    "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                    "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                  },
                  "details": [
                    {
                      "message": "\"amount\" must be a number",
                      "path": [
                        "amount"
                      ],
                      "type": "number.base",
                      "context": {
                        "label": "amount",
                        "value": "a",
                        "key": "amount"
                      }
                    }
                  ]
                }
              },
              "properties": {
                "_original": {
                  "type": "object",
                  "properties": {
                    "amount": {
                      "type": "string"
                    },
                    "sender": {
                      "type": "string"
                    },
                    "recipient": {
                      "type": "string"
                    }
                  }
                },
                "details": {
                  "type": "array",
                  "uniqueItems": true,
                  "minItems": 1,
                  "items": {
                    "type": "object",
                    "properties": {
                      "message": {
                        "type": "string"
                      },
                      "path": {
                        "type": "array",
                        "items": {
                          "type": "string"
                        }
                      },
                      "type": {
                        "type": "string"
                      },
                      "context": {
                        "type": "object",
                        "properties": {
                          "label": {
                            "type": "string"
                          },
                          "value": {
                            "type": "string"
                          },
                          "key": {
                            "type": "string"
                          }
                        }
                      }
                    }
                  }
                }
              }
            },
            "examples": {
              "error-body-validation": {
                "$ref": "#/components/examples/bodyValidation"
              }
            }
          }
        }
      },
      "axiosError": {
        "description": "Internal Server Error",
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "message": "Request failed with status code 400",
                  "name": "Error",
                  "stack": "Error: Request failed with status code 400\n    at createError (/home/giocom/com/apps/blockchain-js/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/home/giocom/com/apps/blockchain-js/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/home/giocom/com/apps/blockchain-js/node_modules/axios/lib/adapters/http.js:293:11)\n    at IncomingMessage.emit (node:events:402:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
                  "config": {
                    "transitional": {
                      "silentJSONParsing": true,
                      "forcedJSONParsing": true,
                      "clarifyTimeoutError": false
                    },
                    "transformRequest": [
                      null
                    ],
                    "transformResponse": [
                      null
                    ],
                    "timeout": 0,
                    "xsrfCookieName": "XSRF-TOKEN",
                    "xsrfHeaderName": "X-XSRF-TOKEN",
                    "maxContentLength": -1,
                    "maxBodyLength": -1,
                    "headers": {
                      "Accept": "application/json, text/plain, */*",
                      "Content-Type": "application/json",
                      "User-Agent": "axios/0.24.0",
                      "Content-Length": 38
                    },
                    "method": "post",
                    "url": "http://localhost:3002/api/v1/register-node",
                    "data": "{\"newNodeUrl\":\"http://localhost:3003\"}"
                  },
                  "status": 400
                }
              },
              "properties": {
                "message": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                },
                "stack": {
                  "type": "string"
                },
                "config": {
                  "type": "object",
                  "properties": {
                    "transitional": {
                      "type": "object",
                      "properties": {
                        "silentJSONParsing": {
                          "type": "boolean"
                        },
                        "forcedJSONParsing": {
                          "type": "boolean"
                        },
                        "clarifyTimeoutError": {
                          "type": "boolean"
                        }
                      }
                    },
                    "transformRequest": {
                      "type": "array",
                      "items": {}
                    },
                    "transformResponse": {
                      "type": "array",
                      "items": {}
                    },
                    "timeout": {
                      "type": "number"
                    },
                    "xsrfCookieName": {
                      "type": "string"
                    },
                    "xsrfHeaderName": {
                      "type": "string"
                    },
                    "maxContentLength": {
                      "type": "number"
                    },
                    "maxBodyLength": {
                      "type": "number"
                    },
                    "headers": {
                      "type": "object",
                      "properties": {
                        "Accept": {
                          "type": "string"
                        },
                        "Content-Type": {
                          "type": "string"
                        },
                        "User-Agent": {
                          "type": "string"
                        },
                        "Content-Length": {
                          "type": "number"
                        }
                      }
                    },
                    "method": {
                      "type": "string"
                    },
                    "url": {
                      "type": "string"
                    },
                    "data": {
                      "type": "string"
                    }
                  }
                },
                "status": {
                  "type": "number"
                }
              }
            },
            "examples": {
              "request-error": {
                "$ref": "#/components/examples/axiosError"
              }
            }
          }
        }
      }
    },
    "examples": {
      "blockchain": {
        "value": {
          "chain": [
            {
              "index": 1,
              "timestamp": 1642008048586,
              "transactions": [],
              "nonce": 0,
              "hash": "0",
              "prevBlockHash": "0"
            },
            {
              "index": 2,
              "timestamp": 1642010815329,
              "transactions": [
                {
                  "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                  "amount": 10,
                  "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                  "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                }
              ],
              "nonce": 54068,
              "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
              "prevBlockHash": "0"
            }
          ],
          "pendingTransactions": [
            {
              "transactionId": "6d291ca073d211ec8f13b941e4a40c7b",
              "amount": 12.5,
              "sender": "00",
              "recipient": "fc0c42a073cb11ec8f13b941e4a40c7b"
            }
          ],
          "currentNodeUrl": "http://localhost:3001",
          "networkNodes": [
            "http://localhost:3002",
            "http://localhost:3003"
          ]
        }
      },
      "transaction": {
        "value": {
          "amount": 20,
          "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
          "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
        }
      },
      "bodyValidation": {
        "value": {
          "_original": {
            "amount": "a",
            "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
            "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
          },
          "details": [
            {
              "message": "\"amount\" must be a number",
              "path": [
                "amount"
              ],
              "type": "number.base",
              "context": {
                "label": "amount",
                "value": "a",
                "key": "amount"
              }
            }
          ]
        }
      },
      "registerNode": {
        "value": {
          "newNodeUrl": "http://localhost:3002"
        }
      },
      "alreadyExist": {
        "value": {
          "note": "Node already exists"
        }
      },
      "networkNodes": {
        "value": {
          "allNetworkNodes": [
            "http://localhost:3004",
            "http://localhost:3005"
          ]
        }
      },
      "newBlock": {
        "value": {
          "newBlock": {
            "index": 2,
            "timestamp": 1642010815329,
            "transactions": [
              {
                "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                "amount": 10,
                "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
              }
            ],
            "nonce": 54068,
            "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
            "prevBlockHash": "0"
          }
        }
      },
      "axiosError": {
        "value": {
          "message": "Request failed with status code 400",
          "name": "Error",
          "stack": "Error: Request failed with status code 400",
          "config": {
            "transitional": {
              "silentJSONParsing": true,
              "forcedJSONParsing": true,
              "clarifyTimeoutError": false
            },
            "transformRequest": [
              null
            ],
            "transformResponse": [
              null
            ],
            "timeout": 0,
            "xsrfCookieName": "XSRF-TOKEN",
            "xsrfHeaderName": "X-XSRF-TOKEN",
            "maxContentLength": -1,
            "maxBodyLength": -1,
            "headers": {
              "Accept": "application/json, text/plain, */*",
              "Content-Type": "application/json",
              "User-Agent": "axios/0.24.0",
              "Content-Length": 38
            },
            "method": "post",
            "url": "http://localhost:3002/api/v1/register-node",
            "data": "{\"newNodeUrl\":\"http://localhost:3003\"}"
          },
          "status": 400
        }
      }
    },
    "requestBodies": {
      "transaction": {
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "amount": 20,
                  "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                  "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                }
              },
              "properties": {
                "amount": {
                  "type": "number"
                },
                "sender": {
                  "type": "string",
                  "description": "Sender address.",
                  "minLength": 2,
                  "maxLength": 64
                },
                "recipient": {
                  "type": "string",
                  "description": "Recipient address.",
                  "minLength": 32,
                  "maxLength": 64
                }
              },
              "required": [
                "amount",
                "sender",
                "recipient"
              ]
            },
            "examples": {
              "transaction-body": {
                "$ref": "#/components/examples/transaction"
              }
            }
          }
        }
      },
      "registerNode": {
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "newNodeUrl": "http://localhost:3002"
                }
              },
              "properties": {
                "newNodeUrl": {
                  "type": "string"
                }
              },
              "required": [
                "newNodeUrl"
              ]
            },
            "examples": {
              "register-body": {
                "$ref": "#/components/examples/registerNode"
              }
            }
          }
        }
      },
      "networkNodes": {
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "allNetworkNodes": [
                    "http://localhost:3004",
                    "http://localhost:3005"
                  ]
                }
              },
              "properties": {
                "allNetworkNodes": {
                  "type": "array",
                  "items": {
                    "type": "string"
                  }
                }
              },
              "required": [
                "allNetworkNodes"
              ]
            },
            "examples": {
              "bulk-body": {
                "$ref": "#/components/examples/networkNodes"
              }
            }
          }
        }
      },
      "newBlock": {
        "content": {
          "application/json": {
            "schema": {
              "description": "",
              "type": "object",
              "x-examples": {
                "example-1": {
                  "newBlock": {
                    "index": 2,
                    "timestamp": 1642010815329,
                    "transactions": [
                      {
                        "transactionId": "3e5c856073d211ec8f13b941e4a40c7b",
                        "amount": 10,
                        "sender": "cf942722a4ecc3b89e3911fbb8f84071bca39142aba93dc9b971bb06ae980819",
                        "recipient": "a6d0f357931dfc871f97164d8c848501e25377a9a327d93241e0abd0add383ea"
                      }
                    ],
                    "nonce": 54068,
                    "hash": "00008410e1b515081b3c124abe1c04da08cae7acedddc79c471e7a7794d81520",
                    "prevBlockHash": "0"
                  }
                }
              },
              "properties": {
                "newBlock": {
                  "type": "object",
                  "required": [
                    "index",
                    "timestamp",
                    "transactions",
                    "nonce",
                    "hash",
                    "prevBlockHash"
                  ],
                  "properties": {
                    "index": {
                      "type": "number"
                    },
                    "timestamp": {
                      "type": "number"
                    },
                    "transactions": {
                      "type": "array",
                      "uniqueItems": false,
                      "items": {
                        "type": "object",
                        "properties": {
                          "transactionId": {
                            "type": "string",
                            "minLength": 32,
                            "maxLength": 32
                          },
                          "amount": {
                            "type": "number",
                            "minimum": 0
                          },
                          "sender": {
                            "type": "string",
                            "minLength": 2,
                            "maxLength": 64
                          },
                          "recipient": {
                            "type": "string",
                            "minLength": 32,
                            "maxLength": 64
                          }
                        },
                        "required": [
                          "transactionId",
                          "amount",
                          "sender",
                          "recipient"
                        ]
                      }
                    },
                    "nonce": {
                      "type": "number"
                    },
                    "hash": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 64
                    },
                    "prevBlockHash": {
                      "type": "string",
                      "minLength": 1,
                      "maxLength": 64
                    }
                  }
                }
              },
              "required": [
                "newBlock"
              ]
            },
            "examples": {
              "block-body": {
                "$ref": "#/components/examples/newBlock"
              }
            }
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "blockchain"
    },
    {
      "name": "mine"
    },
    {
      "name": "register"
    },
    {
      "name": "transaction"
    }
  ]
}